[project]
name = "test-proj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "paypal-aiplatform-sdk>=1.84.0",
    "requests>=2.32.3",
]
